#!/usr/bin/env node
// 从 codex-mobile-pro/skills/*/SKILL.md 提取 name+description，生成 data/skills.js + data/skills.json
// 用法：node scripts/gen-data.mjs <skills 目录>   （默认 ../../skills，即 codex-mobile-pro/skills）
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = fileURLToPath(new URL('.', import.meta.url))
const skillsRoot = resolve(process.argv[2] ?? join(here, '../../skills'))
const outDir = join(here, '../data')

function parseFrontmatter(text) {
  // 提取 YAML frontmatter 里的 name / description（单行或折叠块）
  const name = text.match(/^name:\s*(.+)$/m)?.[1]?.trim()
  const descLine = text.match(/^description:\s*(.+)$/m)?.[1]?.trim()
  let description = descLine
  if (!description) {
    // 多行折叠：description: | 后接若干行
    const block = text.match(/^description:\s*\|\s*$/m)
    if (block) {
      const lines = []
      for (const l of text.slice(block.index).split('\n').slice(1)) {
        if (/^\S/.test(l) || l.trim() === '') break
        lines.push(l.trim())
      }
      description = lines.join(' ')
    }
  }
  return { name, description }
}

const entries = (await readdir(skillsRoot, { withFileTypes: true }))
  .filter((e) => e.isDirectory())
  .sort((a, b) => a.name.localeCompare(b.name))

const skills = []
for (const e of entries) {
  const dir = join(skillsRoot, e.name)
  let text = ''
  try { text = await readFile(join(dir, 'SKILL.md'), 'utf8') } catch { /* 无 SKILL.md 则跳过 */ }
  if (!text) continue
  const { name, description } = parseFrontmatter(text)
  if (!name || !description) {
    console.error(`[gen] skip ${e.name}: missing name/description in frontmatter`)
    continue
  }
  skills.push({ name, description })
}

await mkdir(outDir, { recursive: true })
const json = JSON.stringify(skills, null, 2) + '\n'
await writeFile(join(outDir, 'skills.json'), json)
await writeFile(join(outDir, 'skills.js'), `// Auto-generated by scripts/gen-data.mjs — do not edit by hand.\n// ${skills.length} skills extracted from codex-mobile-pro/skills (see scripts/gen-data.mjs)\nexport const skills = ${json.replace(/\n/g, '\n  ')}`)
console.log(`[gen] wrote ${skills.length} skills to data/skills.js + data/skills.json`)
