/// ====================================================================
/// Ubuntu APT 源管理（Coding Runtime 网络层修复）
///
/// 背景（2026-08 真机根因审计）：
///   App 部署的 Ubuntu noble rootfs（termux proot-distro v4.18.0）
///   默认 apt 源为 `http://ports.ubuntu.com/ubuntu-ports`（HTTP:80）。
///   部分网络环境下该 TCP 连接间歇性失败，导致
///   `apt-get install` 报 `E: Failed to fetch ... exit=100`。
///
/// 修复策略（只动 APT 网络层，不修改 rootfs 构建 / proot / loader）：
///   - 保持 rootfs 原样，仅在部署/安装阶段按需生成/覆盖
///     `/etc/apt/sources.list`（参照 ensureResolvConf 先例）。
///   - fallback 链：官方 HTTP → 官方 HTTPS → 清华 → 阿里云 → USTC。
///   - 每个源独立验证：apt-get update（TCP/HTTPS + 索引下载）
///     → apt-get install（.deb 下载 + 安装），不做「仅 DNS」判断。
///   - 首次覆盖前备份原始配置到 sources.list.orig，便于回滚诊断。
///
/// 约束：
///   - 不修改 Ubuntu rootfs 的镜像内容（仅 /etc/apt 配置）。
///   - 不使用 Termux 源（App 目标就是摆脱 Termux 依赖）。
/// ====================================================================
library;

import 'dart:io';

import '../../core/logger/log_service.dart';

/// 单个 apt 源描述
class AptSourceEntry {
  /// 源名称（日志 / 诊断用，如 official-https / tuna）
  final String name;

  /// 源基础 URI（如 https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports）
  final String baseUri;

  /// 区域标签（'cn' = 中国大陆镜像）
  final String region;

  /// 优先级（越大越优先尝试）
  final int priority;

  const AptSourceEntry({
    required this.name,
    required this.baseUri,
    this.region = '',
    this.priority = 50,
  });
}

/// Ubuntu apt 源管理器
class AptSourceManager {
  /// rootfs 根目录（绝对路径，宿主机视角）
  final String rootfsDir;

  const AptSourceManager(this.rootfsDir);

  /// Ubuntu 版本代号（App 部署的是 noble LTS）
  static const String codename = 'noble';

  /// 组件（与 proot-distro noble rootfs 出厂一致，不含 deb-src）
  static const String components = 'main universe multiverse';

  /// 签名 keyring（rootfs 内 Debian 风格路径，镜像与官方同签）
  static const String keyring =
      '/usr/share/keyrings/ubuntu-archive-keyring.gpg';

  /// 默认 fallback 链（按优先级降序）。
  ///
  /// 出厂源（官方 HTTP）不在列表中显式出现——读取当前配置后动态拼装。
  static const List<AptSourceEntry> fallbackChain = [
    AptSourceEntry(
      name: 'official-https',
      baseUri: 'https://ports.ubuntu.com/ubuntu-ports',
      priority: 90,
    ),
    AptSourceEntry(
      name: 'tuna',
      baseUri: 'https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports',
      region: 'cn',
      priority: 80,
    ),
    AptSourceEntry(
      name: 'aliyun',
      baseUri: 'https://mirrors.aliyun.com/ubuntu-ports',
      region: 'cn',
      priority: 75,
    ),
    AptSourceEntry(
      name: 'ustc',
      baseUri: 'https://mirrors.ustc.edu.cn/ubuntu-ports',
      region: 'cn',
      priority: 70,
    ),
  ];

  /// 生成 sources.list 内容（经典 deb 行格式，与出厂一致）
  String buildSourcesList(AptSourceEntry src) {
    final buf = StringBuffer()
      ..writeln('# Generated by Codex Mobile Pro Runtime (apt source fallback)')
      ..writeln('# Source: ${src.name} (${src.baseUri})')
      ..writeln('# 原始出厂配置备份于 /etc/apt/sources.list.orig');
    for (final suite in [
      codename,
      '$codename-updates',
      '$codename-security',
    ]) {
      buf.writeln(
        'deb [signed-by="$keyring"] ${src.baseUri} $suite $components',
      );
    }
    return buf.toString();
  }

  /// 读取当前 rootfs 内首个 apt 源 URI（sources.list 或 deb822 .sources）。
  ///
  /// 返回 null 表示无法识别（自定义源 / 文件缺失）。
  Future<String?> readCurrentUri() async {
    final listFile = File('$rootfsDir/etc/apt/sources.list');
    if (await listFile.exists()) {
      final uri = _extractDebLineUri(await listFile.readAsString());
      if (uri != null) return uri;
    }
    final dDir = Directory('$rootfsDir/etc/apt/sources.list.d');
    if (await dDir.exists()) {
      await for (final f in dDir.list()) {
        final name = f.path.split('/').last;
        if (!name.endsWith('.sources') && !name.endsWith('.list')) continue;
        try {
          final content = await File(f.path).readAsString();
          final uri = _extractDebLineUri(content) ?? _extractDeb822Uri(content);
          if (uri != null) return uri;
        } catch (_) {
          // 单个文件损坏不阻断
        }
      }
    }
    return null;
  }

  /// 覆盖 rootfs /etc/apt/sources.list 为指定源（部署阶段，参照 ensureResolvConf）。
  ///
  /// 首次切换前备份出厂配置到 sources.list.orig；
  /// 若存在 deb822 .sources（旧版配置），移为 .disabled 避免新旧源同时生效。
  Future<void> writeSource(AptSourceEntry src) async {
    final aptDir = Directory('$rootfsDir/etc/apt');
    await aptDir.create(recursive: true);
    final listFile = File('${aptDir.path}/sources.list');

    if (await listFile.exists() &&
        !await File('${aptDir.path}/sources.list.orig').exists()) {
      await listFile.copy('${aptDir.path}/sources.list.orig');
    }

    final dDir = Directory('${aptDir.path}/sources.list.d');
    if (await dDir.exists()) {
      await for (final f in dDir.list()) {
        final name = f.path.split('/').last;
        if (!name.endsWith('.sources') && !name.endsWith('.list')) continue;
        if (name.endsWith('.disabled')) continue;
        final bak = '${f.path}.disabled';
        if (!await File(bak).exists()) {
          try {
            await File(f.path).rename(bak);
          } catch (e) {
            LogService.warning(
              'AptSource',
              '禁用旧源配置失败(忽略) ${f.path}: $e',
            );
          }
        }
      }
    }

    await listFile.writeAsString(buildSourcesList(src));
    LogService.info('AptSource', 'apt 源已切换为 ${src.name}: ${src.baseUri}');
  }

  /// 构建 fallback 链（排除当前源，避免重复尝试同一 URI）。
  List<AptSourceEntry> buildFallbackChain({String? currentUri}) {
    final normalized = currentUri?.trim().replaceFirst(RegExp(r'/*$'), '');
    return fallbackChain.where((src) {
      final uri = src.baseUri.trim().replaceFirst(RegExp(r'/*$'), '');
      return uri != normalized;
    }).toList();
  }

  /// 从经典 `deb [opts] <uri> ...` 行提取 URI
  static String? _extractDebLineUri(String content) {
    final re =
        RegExp(r'^\s*deb\s+(\[[^\]]*\]\s+)?(\w+://\S+)', multiLine: true);
    final m = re.firstMatch(content);
    return m?.group(2);
  }

  /// 从 deb822 格式提取 `URIs: <uri>`
  static String? _extractDeb822Uri(String content) {
    final re = RegExp(r'^\s*URIs:\s*(\S+)', multiLine: true);
    final m = re.firstMatch(content);
    return m?.group(1);
  }
}
